.PHONY: build
build:
	(cd btm_cgs && make -f ../common-makefile)
	(cd btm_scvb0 && make -f ../common-makefile)
	(cd sptm_cgs && make -f ../common-makefile)
	(cd btm_scvb0_v2 && make -f ../common-makefile)
	(cd btm_scvb0_v2_alpha && make -f ../common-makefile)
	(cd btm_scvb0_v2_beta && make -f ../common-makefile)
.PHONY: clean
clean:
	(cd btm_cgs && make -f ../common-makefile clean)
	(cd btm_scvb0 && make -f ../common-makefile clean)
	(cd sptm_cgs && make -f ../common-makefile clean)
	(cd btm_scvb0_v2 && make -f ../common-makefile clean)
	(cd btm_scvb0_v2_alpha && make -f ../common-makefile)
	(cd btm_scvb0_v2_beta && make -f ../common-makefile)
